METHOD:
  NAME: MEMO
  OPTIM_METHOD: sgd
  OPTIM_LR: 0.005
  OPTIM_STEPS: 1
  NORM_MEAN: [0.5, 0.5, 0.5]
  NORM_STD: [0.5, 0.5, 0.5]
  AUG_BATCH_SIZE : 4

MODEL:
  NAME: wide_resnet28_10
  BACKEND: robustbench

DATA:
  BATCH_SIZE: 4
  NUM_SAMPLES: 10
