METHOD:
  NAME: SHOT
  OPTIM_METHOD: sgd
  OPTIM_LR: 0.005
  OPTIM_STEPS: 1
  NORM_MEAN: [0.5, 0.5, 0.5]
  NORM_STD: [0.5, 0.5, 0.5]

MODEL:
  NAME: wide_resnet28_10
  BACKEND: robustbench
DATA:
  BATCH_SIZE: 4
  NUM_SAMPLES: 12 # 배치 사이즈에 정수배여야 동작함.
