# AVAILABLE_BACKEND = ["robustbench", "torchvision", "huggingface"]
# AVAILABLE_ROBUST_MODEL = ["Standard"]
# AVAILABLE_CUSTOM_MODEL = ["resnet26", "wide_resnet28_10"]
# AVAILABLE_OPTIM = ["adam"]
METHOD:
  NAME: Source

MODEL:
  NAME: wide_resnet28_10
  BACKEND: robustbench


DATA:
  NUM_SAMPLES: 100
  BATCH_SIZE: 100
