MODEL:
  NAME: 'resnet26'  # ResNet26 모델 사용
  BACKEND: 'custom'  # default.py의 BACKEND 키와 일치
  ADAPTATION: 'MEMO'  # MEMO 메소드 사용
  GROUP_NORM: 8  # GroupNorm의 group 수
  NUM_CLASSES: 10  # CIFAR-10의 클래스 수

OPTIM:
  METHOD: 'sgd'  # MEMO는 SGD optimizer 사용
  LR: 0.005  # memo 기본값과 동일
  STEPS: 1  # adaptation 반복 횟수

DATA:
  BATCH_SIZE: 32  # memo  기본값과 동일
  NUM_WORKERS: 8  # memo  workers와 동일
  NORM:
    MEAN: [0.5, 0.5, 0.5]  # memo  NORM과 동일
    STD: [0.5, 0.5, 0.5]
  # for local
  # ROOT: 'dataset/CIFAR-10-C'

SHIFT:
  TYPE: [
    'gaussian_noise', 'shot_noise', 'impulse_noise',
    'defocus_blur', 'glass_blur', 'motion_blur', 'zoom_blur',
    'snow', 'frost', 'fog', 'brightness',
    'contrast', 'elastic_transform', 'pixelate', 'jpeg_compression'
  ]  # memo 의 CORRUPTIONS와 동일
  SEVERITY: [1, 2, 3, 4, 5]  # memo 의 LEVELS와 동일 